const actionTypes = {
  INCREMENT_BIRD_INDEX: 'INCREMENT_BIRD_INDEX',
  RESET_BIRD_INDEX: 'RESET_BIRD_INDEX',
  UPDATE_MAIN_SCORE: 'UPDATE_MAIN_SCORE',
  UPDATE_BIRDS_LIST: 'UPDATE_BIRDS_LIST',
  UPDATE_BIRD_ANSWERS: 'UPDATE_BIRD_ANSWERS',
};

export default actionTypes;
