const actionTypes = {
  INCREMENT_BIRD_INDEX: 'INCREMENT_BIRD_INDEX',
  INCREMENT_QUESTION_INDICATOR: 'INCREMENT_QUESTION_INDICATOR',
  DECREMENT_CURRENT_SCORE: 'DECREMENT_CURRENT_SCORE',
  RESET_CURRENT_SCORE: 'RESET_CURRENT_SCORE',
  RESET_QUESTION_INDICATOR: 'RESET_QUESTION_INDICATOR',
  RESET_BIRD_INDEX: 'RESET_BIRD_INDEX',
  RESET_MAIN_SCORE: 'RESET_MAIN_SCORE',
  UPDATE_MAIN_SCORE: 'UPDATE_MAIN_SCORE',
  UPDATE_BIRDS_LIST: 'UPDATE_BIRDS_LIST',
  UPDATE_BIRD_ANSWERS: 'UPDATE_BIRD_ANSWERS',
  UPDATE_EVENT_DATA: 'UPDATE_EVENT_DATA',
  CHANGE_IS_CLICKED_OF_BIRD_ANSWER: 'CHANGE_IS_CLICKED_OF_BIRD_ANSWER',
};

export default actionTypes;
